version: '3'

services:
  # Frontend Service
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./Dockerfile
    command: 'npx nx serve frontend'
    ports:
      - '4200:4200'
    depends_on:
      - backend

  # Backend Service
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    command: 'npx nx serve backend'
    ports:
      - '3000:3000'
